"""Run a :class:`~manipulation_kit.primitives.Plan` on a real D1, through d1-firmwared.

THE TRANSPORT CHOICE, stated once and argued
--------------------------------------------
Two ways exist to put a joint path on the arms, and the daemon offers both:

``POST /v1/arm/move_joints_both``, streamed at 50 Hz
    What VR teleop does, because teleop has no path — it has whatever the
    operator's hand did in the last 20 ms. Each POST is one guarded dual-arm
    pose. The cost is that the timing lives on THIS side of the socket: a GC
    pause, a scheduler hiccup or a slow reply lands as a gap in the command
    stream, the controller's ``frame_miss_count`` climbs, and a post-stall
    flush arrives as one large step (which is why teleop carries an anti-lunge
    clamp at all).

``POST /v1/arm/trajectory/start``, one upload
    What a PLAN is. The daemon takes up to 10 000 absolute-time waypoints,
    plays them on its own 1 ms tokio ticker, re-checks EVERY sampled pose
    against its own Rust motion guard, enforces a 350 deg/s slew limit at
    runtime, refuses to start unless the first pose is within 3 degrees of
    measured feedback and the arm is in a clean position or torque hold, and
    cancels cleanly — including automatically, when the arm lease is preempted
    out from under us.

**This executor's default is ``trajectory``**, because the thing that makes
streaming necessary — a target that is not known until the moment it is sent —
is exactly what a pre-checked plan does not have. Every joint step in a
:class:`Plan` was already solved, step-clamped and guard-checked before the
first byte moved; handing all of them to the daemon at once moves the timing to
the component with a real-time loop and adds a second, independent guard pass
over the whole path. Streaming stays available (``transport="stream"``) for the
case that genuinely is a stream — a corrective ``Nudge`` inside a visual servo
loop, where the next target depends on the last frame — and it is exercised by
the tests, so the fallback is not decorative.

Everything else here is the part consumers kept re-deriving:

* the **arm lease** at class ``policy`` (teleop and the console claim
  ``operator`` and outrank us — a person at the robot always wins), heartbeat
  while we hold it, released on exit, and ``epoch`` watched so a preemption we
  survived is not mistaken for uninterrupted possession;
* **position mode with the run's own velocity/acceleration ratios**, re-sent
  even when the arm is already holding position, because ``recover`` leaves its
  own ratios behind and a policy served at those drove the right arm to ~90 Nm
  on d1-2 (2026-09-10);
* the **140 deg/s joint rate clamp** dx-vr-teleop runs (7 deg per tick at its
  20 Hz keepalive), applied here per command interval;
* **grip presets, not numbers**: the preset owns the stop torque (d1-firmware
  PR #55), so ``soft``/``firm``/``strong`` is the whole vocabulary.

Install: ``pip install 'manipulation-kit[firmware]'``. The extra carries the
runtime dependencies of a **generated** client and nothing else — no private
package to pin, no git URL. The client itself is bundled (``_client/``,
generated by ``openapi-python-client`` from the daemon's OpenAPI document) and
is checked against the live daemon on the first connect: same document, same
client; a newer firmware and it is regenerated on the spot. See
:mod:`manipulation_kit.executors.firmware.ensure`.
"""

from __future__ import annotations

import math
import os
import threading
import time
import uuid
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Sequence

import numpy as np

from ...arms import safety, sides
from ...executor import (ARRIVE_TIMEOUT_S, ARRIVE_TOL_RAD, BARRIER_FAILED,
                        CONTACT, CONTACT_BASELINE_SAMPLES, CONTACT_FAULT,
                        CONTACT_GUARD, CONTROLLER_FAULT, JOINT_SLICE,
                        MAX_TRAVEL, SIDES, TRANSPORT_ERROR, UNMEASURED,
                        ArrivalReport, ContactReport, ContactWatch, LiftState,
                        NeckState, RawState, RunReport, SettleReport,
                        StrokeReport, ToolGate, WIRE_DIM, _final_arrival,
                        arrive_labels, barrier_refusal, contact_kin, contact_report,
                        controller_fault, fault_refusal, hold_refusal,
                        retract_path, stroke_refusal)
from ...primitives.types import (ContactCriterion, ContactStep, GripStep,
                                 JointStep, Plan, SettleStep)
from .client import (FAULT_KINDS, SETTLED_KINDS, UNFINISHED_KINDS, _word,
                     check_waypoints,
                     hand_state, joint_state)
from .client import lift_state as _lift_state
from .client import neck_state as _neck_state
from .errors import (FirmwareUnavailable, LeasePreempted,  # noqa: F401
                     RateRefused, TrajectoryInvalid)

# --------------------------------------------------------------------------- #
# constants, each with the measurement behind it
# --------------------------------------------------------------------------- #

#: Command rate. ``dx-vr-teleop``'s ``HOME_RATE_HZ = 50.0`` ("ramp step rate —
#: VR tick parity"): the rate the arms are actually driven at on this robot.
STREAM_HZ = 50.0

#: Per-joint rate ceiling at FULL speed [deg/s]. ``dx-vr-teleop``'s anti-lunge clamp is
#: ``JOINT_DELTA_CLAMP_DEG = 7.0`` per tick at its 20 Hz keepalive, i.e.
#: 140 deg/s — "~2-3x the fastest plausible human teleop joint speed", so
#: continuous motion passes through untouched while a single-tick warp is
#: spread over several commands. Expressed as a RATE here because this executor
#: runs at a different tick than the keepalive it was measured at, and a
#: per-tick copy of the number would mean something different at 50 Hz.
MAX_JOINT_RATE_DEG_S = 140.0

#: How long ONE blocking gripper stroke may take [s], when the document does
#: not say. d1-firmwared's ``POST /v1/gripper/{side}/set`` blocks until the
#: stroke is done and publishes its own bound as the operation's
#: ``x-timeout-seconds`` (40 s on 0.3.0), which is what the executor uses; this
#: is the fallback for a document without it. 20 s is what a real firm close
#: on d1-2 needed with margin (2026-09-22, when the client's 2 s default cut
#: the stroke off and the example injected 20 s into the client by hand).
DEFAULT_STROKE_TIMEOUT_S = 20.0


def schedule_rate_deg_s(vel_ratio: float) -> float:
    """The joint rate the trajectory schedule is timed at [deg/s].

    The daemon runs position mode at ``vel_ratio`` x full speed, so a schedule
    timed at the full-speed ceiling runs AHEAD of the arm: at the default
    0.15 the arm moves about 20 deg/s behind timestamps seven times faster,
    every large move "arrives late" and the arrival barrier fails while the
    arm is still moving (d1-2 run4, 2026-09-22: "still moving after 1.5 s,
    worst joint 18.2 deg/s", tool 190 mm off). So the schedule is timed at
    the speed the ratio this executor INSTALLS will give — derived here, once,
    rather than by each caller.
    """
    return MAX_JOINT_RATE_DEG_S * float(vel_ratio)

#: Interpolation window at the start of a trajectory [s]. The daemon refuses a
#: trajectory whose first waypoint is more than 3 degrees from measured
#: feedback, so every upload begins AT the measured pose; this is how long it
#: is given to reach the plan's first knot. Three 50 Hz ticks — long enough
#: that the controller interpolates into the motion instead of stepping into
#: it, short enough not to feel like a pause.
INTERPOLATION_S = 0.060

#: Velocity / acceleration ratios for position mode, as FRACTIONS in [0, 1].
#: The daemon clamps anything above 1, so passing the vendor SDK's percent
#: integers unconverted asks for 800% and gets 100% — every firmware run on
#: d1-2 up to 2026-09-10 drove the arms flat out and faulted the right arm at
#: the grasp. 0.15 is d1-inference's default.
DEFAULT_VEL_RATIO = 0.15
DEFAULT_ACC_RATIO = 0.15

#: Lease class. ``operator`` is a person at the robot (teleop, the console) and
#: outranks us; ``ambient`` is the un-classed default nobody can be displaced
#: by. A planned primitive is policy-grade motion, so: ``policy``.
LEASE_CLASS = "policy"
DEFAULT_TTL_S = 30
#: Fraction of the TTL after which the lease is renewed. A third: two renewals
#: are missed before the daemon can take the arms back.
HEARTBEAT_FRACTION = 1.0 / 3.0


def default_holder() -> str:
    """A holder string unique to THIS session.

    Every process defaulting to the literal ``"manipulation-kit"`` means the
    daemon cannot tell two of them apart: a second one renews the first one's
    lease, and a ``DELETE`` from either hands back the arms the other is
    driving. The name still starts with the package so a person reading
    ``GET /v1/arm/lease`` knows what has the robot.
    """
    return f"manipulation-kit/{os.getpid()}-{uuid.uuid4().hex[:8]}"


#: Kept for consumers that pinned the old literal. It is NOT the default.
DEFAULT_HOLDER = "manipulation-kit"

#: The largest single-command joint change this transport will put on the
#: wire [deg]. One POST is one absolute target the controller interpolates
#: to, so a knot bigger than the planner's own per-tick cap is a lunge —
#: and the answer is to REFUSE it, not to clip it into something the geometry
#: no longer describes (R4).
MAX_COMMAND_STEP_DEG = math.degrees(safety.MAX_JOINT_STEP_RAD)

#: Largest gap [deg] between the commanded and the measured pose at which
#: position control may be engaged from idle. Beyond it the controller would
#: snap to a stale command — on d1-2 (2026-09-10) one joint's command sat 48
#: degrees from its measurement.
ANCHOR_GAP_DEG = 3.0


def _given_text(value: Any) -> str:
    """A generated optional string (``None`` / ``Unset`` / text) as text."""
    if value is None or type(value).__name__ == "Unset":
        return "(no message)"
    return str(value)


def _wire_side(side: str) -> str:
    """Logical side -> the daemon's path segment. The crossover lives in
    :mod:`manipulation_kit.arms.sides`; this is the only place it is spelt."""
    return sides.SDK_SIDE[sides.check(side)].lower()


def _default_client(base_url: str, policy: str, cache_dir):
    """The client this executor drives when the caller injected none.

    Deliberately NOT a published package: the tree is generated, bundled, and
    re-generated against the daemon's own OpenAPI document at this moment — see
    :mod:`manipulation_kit.executors.firmware.ensure` for why, and for what
    happens on a machine that cannot run the generator.
    """
    from .client import FirmwareClient  # noqa: PLC0415 - imports httpx

    try:
        return FirmwareClient(base_url, policy=policy, cache_dir=cache_dir)
    except ImportError as exc:  # pragma: no cover - depends on the venv
        raise FirmwareUnavailable(
            "manipulation_kit.executors.firmware needs the runtime deps of its "
            "generated client: pip install 'manipulation-kit[firmware]'") from exc


@dataclass(frozen=True)
class Lease:
    """The daemon's published view of who holds the arms."""

    holder: str
    lease_class: str
    epoch: int
    ttl_s: int
    expires_in_s: int
    preempted_from: Optional[str] = None

    @classmethod
    def parse(cls, data: Any) -> "Lease":
        return cls(holder=str(data["holder"]),
                   lease_class=str(data.get("class", "ambient")),
                   epoch=int(data.get("epoch", 0)),
                   ttl_s=int(data.get("ttl_s", 0)),
                   expires_in_s=int(data.get("expires_in_s", 0)),
                   preempted_from=data.get("preempted_from"))


class FirmwareExecutor:
    """An :class:`~manipulation_kit.executor.Executor` over d1-firmwared.

    Use it as a context manager: the lease is taken on entry and handed back on
    exit, including on an exception, because a crashed consumer that keeps the
    arms until its TTL expires is a robot nobody can drive.

        with FirmwareExecutor(base_url="http://d1-2:4750") as robot:
            run(plan, robot)

    ``client`` may be injected — that is how the tests drive a fake with no
    socket, and how a consumer that already has a connection reuses it. When it
    is not, one is built with
    :class:`~manipulation_kit.executors.firmware.client.FirmwareClient`, whose
    construction is where the daemon's OpenAPI document is fetched and compared
    against the bundled snapshot. ``client_policy`` is passed straight through:
    ``"auto"`` regenerates on drift and warns if it cannot, ``"strict"`` refuses
    to run against a daemon it cannot match, ``"bundled"`` never asks.
    """

    def __init__(self, client: Any = None, *,
                 base_url: str = "http://127.0.0.1:4750",
                 holder: Optional[str] = None,
                 lease_class: str = LEASE_CLASS,
                 ttl_s: int = DEFAULT_TTL_S,
                 transport: str = "trajectory",
                 hz: float = STREAM_HZ,
                 vel_ratio: float = DEFAULT_VEL_RATIO,
                 acc_ratio: float = DEFAULT_ACC_RATIO,
                 max_joint_rate_deg_s: Optional[float] = None,
                 grip: str = "soft",
                 heartbeat: bool = True,
                 arrive_tol_rad: float = ARRIVE_TOL_RAD,
                 arrive_timeout_s: float = ARRIVE_TIMEOUT_S,
                 stroke_timeout_s: Optional[float] = None,
                 client_policy: str = "auto",
                 client_cache_dir=None,
                 sleep=time.sleep, clock=time.monotonic):
        if transport not in ("trajectory", "stream"):
            raise ValueError("transport must be 'trajectory' or 'stream', "
                             f"got {transport!r}")
        for name, ratio in (("vel_ratio", vel_ratio), ("acc_ratio", acc_ratio)):
            if not 0.0 < float(ratio) <= 1.0:
                raise ValueError(f"{name} is a FRACTION in (0, 1]; the daemon "
                                 f"clamps anything above 1, so {ratio!r} asks "
                                 f"for full speed. Divide the percent by 100.")
        if max_joint_rate_deg_s is None:
            max_joint_rate_deg_s = schedule_rate_deg_s(vel_ratio)
        self.client = (client if client is not None else
                       _default_client(base_url, client_policy, client_cache_dir))
        if stroke_timeout_s is None:
            documented = getattr(self.client, "operation_timeout_s", None)
            stroke_timeout_s = ((documented("POST", "/v1/gripper/{side}/set")
                                 if documented is not None else None)
                                or DEFAULT_STROKE_TIMEOUT_S)
        # Positive and FINITE, all of them. A NaN hz makes every period a NaN,
        # every sleep a no-op and every deadline unreachable, and nothing
        # downstream would have said so (R14).
        for name, value in (("hz", hz), ("max_joint_rate_deg_s",
                                         max_joint_rate_deg_s),
                            ("arrive_timeout_s", arrive_timeout_s),
                            ("stroke_timeout_s", stroke_timeout_s),
                            ("arrive_tol_rad", arrive_tol_rad)):
            if not (math.isfinite(float(value)) and float(value) > 0.0):
                raise ValueError(f"{name} must be a positive finite number, "
                                 f"got {value!r}")
        if not (math.isfinite(float(ttl_s)) and int(ttl_s) >= 1):
            raise ValueError(f"ttl_s must be at least 1 second, got {ttl_s!r}")
        #: sha256 of the OpenAPI document the client was generated from — the
        #: firmware contract a plan's binding is compared against
        #: (``executor.check_binding``). ``None`` for a client that cannot say.
        self.firmware_spec: Optional[str] = getattr(self.client, "spec_sha256", None)
        self.holder = holder if holder is not None else default_holder()
        self.lease_class = lease_class
        self.ttl_s = int(ttl_s)
        self.transport = transport
        self.hz = float(hz)
        self.period = 1.0 / float(hz)
        self.vel_ratio = float(vel_ratio)
        self.acc_ratio = float(acc_ratio)
        self.max_rate = float(max_joint_rate_deg_s)
        self.grip = grip
        self.arrive_tol_rad = float(arrive_tol_rad)
        self.arrive_timeout_s = float(arrive_timeout_s)
        self.stroke_timeout_s = float(stroke_timeout_s)
        self._sleep = sleep
        self._clock = clock
        self.lease: Optional[Lease] = None
        self._last_sent_deg: Dict[str, np.ndarray] = {}
        self._t0: Optional[float] = None
        self._last_lease_at: float = float("-inf")
        self._epoch: Optional[int] = None
        self._want_heartbeat = bool(heartbeat)
        self._beat: Optional[threading.Thread] = None
        self._stop_beat = threading.Event()
        #: trajectory jobs we started and have not seen finish. Cancelled on
        #: the way out of any failure, so an interrupted consumer does not
        #: leave the arms playing a path nobody is watching.
        self._jobs: List[int] = []
        #: side -> the closedness this executor last COMMANDED and the daemon
        #: accepted. Published as ``HandState.commanded``: the transport
        #: knows what it asked for, and a runner that cannot find it refuses
        #: to move a holding hand (F9).
        self._commanded: Dict[str, float] = {}

    # -- lease ------------------------------------------------------------- #
    def acquire(self, *, strict: bool = False) -> Lease:
        """Take (or heartbeat) the arm lease.

        ``strict`` is for a renewal DURING a run: a changed epoch then means
        we were preempted and got the arms back, so anything in flight is
        stale and the run must stop. At entry a changed epoch is just news.
        """
        data = self.client.request("POST", "/v1/arm/lease", {
            "holder": self.holder, "class": self.lease_class, "ttl_s": self.ttl_s})
        lease = Lease.parse(data)
        self._last_lease_at = self._clock()
        changed = self._epoch is not None and lease.epoch != self._epoch
        self._epoch = lease.epoch
        self.lease = lease
        if changed:
            # A fresh grant means we LOST the arms in between: mode, tool
            # registration and the last-sent pose are all stale now.
            self._last_sent_deg.clear()
            self._t0 = None
            if strict:
                raise LeasePreempted(
                    f"the arm lease epoch moved to {lease.epoch} while this "
                    f"run was in progress"
                    + (f" (preempted from {lease.preempted_from})"
                       if lease.preempted_from else "")
                    + ": the arms were held by somebody else in between, so "
                      "the mode, the ratios and the posture this plan was "
                      "checked against are all stale. Re-observe and replan.")
        return lease

    def renew(self) -> None:
        """Heartbeat if the lease is due. Safe to call from anywhere hot.

        Called from every polling loop and every send, so the lease survives a
        long trajectory, a slow settle and a model turn without anything
        having to remember to renew it. ``acquire`` was the only renewal
        implementation and NOTHING called it periodically (R6).
        """
        if self.lease is None:
            return
        due = self.ttl_s * HEARTBEAT_FRACTION
        if self._clock() - self._last_lease_at >= due:
            self.acquire(strict=True)

    def _heartbeat_loop(self) -> None:
        interval = max(0.05, self.ttl_s * HEARTBEAT_FRACTION)
        while not self._stop_beat.wait(interval):
            try:
                self.acquire()
            except Exception:  # noqa: BLE001 - the run's own calls will see it
                return

    def release(self) -> None:
        """Hand the arms back. Never raises — a failed release must not mask
        the exception that is on its way out of the ``with`` block."""
        self._stop_beat.set()
        beat, self._beat = self._beat, None
        if beat is not None:
            beat.join(timeout=1.0)
        self.cancel_jobs()
        if self.lease is None:
            return
        try:
            self.client.request("DELETE", "/v1/arm/lease", {"holder": self.holder})
        except Exception:  # noqa: BLE001 - see the docstring
            pass
        finally:
            self.lease = None

    def cancel_jobs(self) -> None:
        """Best-effort cancel of every trajectory we started and did not see end.

        ``_play`` used to cancel only on its own deadline, so a status-poll
        exception, a preemption or a Ctrl-C left the daemon playing a path
        with nobody watching it (R6).
        """
        for job in list(self._jobs):
            try:
                self.client.request("POST", f"/v1/arm/trajectory/{job}/cancel", {})
            except Exception:  # noqa: BLE001 - best effort, by definition
                pass
        self._jobs.clear()

    def __enter__(self) -> "FirmwareExecutor":
        self.acquire()
        try:
            self.position_mode()
        except BaseException:
            # HAND THE ARMS BACK. A failed setup used to leave the lease
            # taken until its TTL expired, and the probe confirmed no DELETE
            # was ever sent (R6): a robot nobody can drive for 30 seconds,
            # because the second arm's mode call raised.
            self.release()
            raise
        if self._want_heartbeat:
            self._stop_beat.clear()
            self._beat = threading.Thread(target=self._heartbeat_loop,
                                          name="mkit-lease", daemon=True)
            self._beat.start()
        return self

    def __exit__(self, *_exc) -> None:
        self.release()

    def _holder_body(self, body: Dict[str, Any]) -> Dict[str, Any]:
        return dict(body, holder=self.holder) if self.lease is not None else dict(body)

    # -- setup ------------------------------------------------------------- #
    def position_mode(self) -> None:
        """Put both arms in position control at THIS run's ratios.

        Sent even when the arm already reports ``position``: the ratios are
        part of the request, the daemon's own ``recover`` leaves different ones
        behind, and a policy served at those is the d1-2 90 Nm incident.
        """
        for side in SIDES:
            wire = _wire_side(side)
            state = self.client.arm_state(wire)
            if _word(state.mode) != "position":
                gap = max(abs(c - f) for c, f in
                          zip(state.command_joints, state.feedback_joints))
                if state.error_code or gap > ANCHOR_GAP_DEG:
                    raise FirmwareUnavailable(
                        f"arm {wire} is in mode {_word(state.mode)!r} with error "
                        f"{state.error_code} and its commanded pose is "
                        f"{gap:.1f} deg from the measured one; engaging "
                        f"position control now would snap the arm to a stale "
                        f"command. Recover it explicitly first.")
            self.client.request("POST", f"/v1/arm/{wire}/mode", self._holder_body({
                "mode": "position", "vel_ratio": self.vel_ratio,
                "acc_ratio": self.acc_ratio}))

    # -- Executor protocol ------------------------------------------------- #
    def state(self) -> RawState:
        """Both arms and both hands, from the generated models, field for field.

        Everything the daemon publishes reaches the kit: joints, velocity and
        torque, the controller's mode and error code (a latched arm is
        ``mode == "error"``, read by ``run_steps`` as a
        :data:`~manipulation_kit.executor.CONTROLLER_FAULT`), the jaw gap,
        torque, stroke outcome and fault, the hand's driven-open gap from the
        daemon's own ``open_rad`` — and what this executor has COMMANDED the
        hands to, which only the transport can know.
        """
        arms = {}
        hands = {}
        for side in SIDES:
            wire = _wire_side(side)
            arms[side] = joint_state(self.client.arm_state(wire))
            try:
                report = self.client.gripper_state(wire)
            except Exception:  # noqa: BLE001 - a gripper that cannot be read is
                continue       # UNKNOWN, not "open"; leave it out of the map
            hands[side] = hand_state(report, commanded=self._commanded.get(side))
        return RawState(arms, hands, stamp=self._clock())

    def neck_state(self) -> NeckState:
        """``GET /v1/neck/state`` through the generated operation.

        Pitch is the daemon's LOGICAL sign, unflipped:
        ``description.head_camera.pose_from_neck_state`` owns the convention.
        """
        return _neck_state(self.client.neck_state())

    def lift_state(self) -> LiftState:
        """``GET /v1/slider/state`` through the generated operation."""
        return _lift_state(self.client.slider_state())

    def begin_run(self, plan: Plan = None) -> None:
        """A new plan starts a new clock.

        ``_t0`` was set once, at the first send of the FIRST plan, while
        ``run_steps`` restarts ``t`` at zero for every plan. The second plan's
        points were therefore all overdue the moment they were computed and
        went out in a burst: measured on a fake clock, plan one sent at 0.00 /
        0.02 / 0.04 s and plan two sent all three at 1.04 s after a one-second
        model turn. A per-command 2.8 deg bound is not a 140 deg/s bound when
        the commands have no time between them (R5).
        """
        self._t0 = None

    def end_run(self, plan: Plan = None) -> None:
        self._t0 = None

    def send_joints(self, q16, *, t: float) -> None:
        """One guarded dual-arm POST, paced to ``t``. The TARGET IS NOT ALTERED.

        ``t`` is PLAN time, seconds from the start of THIS run. A caller that
        stalls does not get a burst: the schedule is re-anchored so the points
        after the stall keep their spacing rather than all being overdue at
        once.

        A knot too large for one command is REFUSED
        (:class:`RateRefused`), never clipped. Clipping changed the checked
        geometry, could change the path, and lost the endpoint (R4).
        """
        q = np.asarray(q16, dtype=float).reshape(WIRE_DIM)
        self.renew()
        targets = {side: np.degrees(q[JOINT_SLICE[side]]) for side in SIDES}
        self._check_step(targets)
        now = self._clock()
        if self._t0 is None:
            self._t0 = now
        wait = (self._t0 + float(t)) - now
        if wait > 0:
            self._sleep(wait)
        elif wait < -self.period:
            # LATE. Re-anchor rather than flush: the remaining points keep
            # their planned spacing instead of arriving together.
            self._t0 = now - float(t)
        self.client.request("POST", "/v1/arm/move_joints_both", self._holder_body({
            "a": [float(v) for v in targets["left"]],
            "b": [float(v) for v in targets["right"]],
            "wait": False}))
        self._last_sent_deg = targets

    def _check_step(self, targets: Dict[str, np.ndarray]) -> None:
        """Refuse a command that would be a lunge. Never modify one."""
        for side, deg in targets.items():
            last = self._last_sent_deg.get(side)
            if last is None:
                continue
            step = float(np.max(np.abs(np.asarray(deg, dtype=float) - last)))
            if step > MAX_COMMAND_STEP_DEG + 1e-9:
                raise RateRefused(
                    f"one command would move a {side} joint {step:.2f} deg, "
                    f"over the {MAX_COMMAND_STEP_DEG:.2f} deg this transport "
                    f"puts on the wire in a single POST. Clipping it would "
                    f"send a posture the guard never checked and stop short "
                    f"of the endpoint; re-plan with smaller knots, or upload "
                    f"the plan as a trajectory (the default transport), which "
                    f"stretches the TIME instead of shrinking the motion.")

    def stream_schedule(self, plan: Plan) -> List[float]:
        """Plan time for every joint step, honouring the rate ceiling.

        EVERY KNOT, AT ITS OWN TIME. The geometry is what the guard approved;
        the only thing this is allowed to change is WHEN each knot is sent.
        A segment that would exceed :data:`MAX_JOINT_RATE_DEG_S` at the base
        period gets more time, so the ceiling is met by stretching rather than
        by shortening the motion (R4).

        Raises :class:`RateRefused` before anything is sent when a knot is too
        large for one command at all.
        """
        # Anchored on the posture the plan was CHECKED in, not on whatever
        # the robot reports at this instant: the binding is what guarantees
        # the two agree, and a schedule that silently re-anchors would hide a
        # drift the binding is there to refuse (R8).
        binding = getattr(plan, "binding", None)
        if binding is not None and binding.q0:
            start = {side: np.asarray(q, dtype=float)
                     for side, q in binding.q0.items()}
        else:
            start = self.state().joints
        current = {side: np.degrees(np.asarray(start[side], dtype=float))
                   for side in SIDES if side in start}
        missing = [s for s in SIDES if s not in current]
        if missing:
            raise FirmwareUnavailable(
                f"no measured joints for {missing}; a stream cannot be "
                f"anchored to a posture the robot will not report")
        times: List[float] = []
        t = 0.0
        for index, step in enumerate(plan.joint_steps()):
            nxt = dict(current)
            nxt[step.side] = np.degrees(np.asarray(step.q, dtype=float))
            span = max(float(np.max(np.abs(nxt[side] - current[side])))
                       for side in SIDES)
            if span > MAX_COMMAND_STEP_DEG + 1e-9:
                raise RateRefused(
                    f"the plan contains a {span:.2f} deg joint step, over the "
                    f"{MAX_COMMAND_STEP_DEG:.2f} deg one streamed command may "
                    f"carry. Refused BEFORE anything was sent, because the "
                    f"alternatives are clipping the geometry or truncating "
                    f"the path.")
            dt = max(self.period, span / self.max_rate)
            if index == 0:
                # The same interpolation window the trajectory upload gives
                # its first segment: long enough that the controller
                # interpolates into the motion rather than stepping into it.
                dt = max(dt, INTERPOLATION_S)
            t += dt
            times.append(round(t, 6))
            current = nxt
        return times

    def set_gripper(self, side: str, closedness: float, *, grip: str = "") -> None:
        """One blocking stroke, bounded by :attr:`stroke_timeout_s`.

        The command is recorded only once the daemon ACCEPTED it: a refused
        or timed-out stroke is not a command the hand is under.
        """
        self.renew()
        self.client.gripper_set(_wire_side(side), float(closedness),
                                grip=(grip or self.grip) or None,
                                timeout_s=self.stroke_timeout_s)
        self._commanded[side] = float(closedness)

    # -- barriers ---------------------------------------------------------- #
    def wait_arrived(self, q16, *, tol_rad: float = None,
                     timeout_s: float = None) -> ArrivalReport:
        """Poll the MEASURED joints until they reach the commanded posture.

        Transport completion is not arrival. The trajectory phase says the
        daemon played its last waypoint; this says the arm is there. A stopped
        arm can be short of the target — F5, ten grasps out of ten, the arm
        holding 2.5 deg from the commanded posture with the fingers jammed on
        the table.
        """
        tol = self.arrive_tol_rad if tol_rad is None else float(tol_rad)
        deadline_s = (self.arrive_timeout_s if timeout_s is None
                      else float(timeout_s))
        want = np.asarray(q16, dtype=float).reshape(WIRE_DIM)
        started = self._clock()
        worst = float("nan")
        while True:
            self.renew()
            measured = self.state().joints
            missing = [s for s in SIDES if s not in measured]
            if missing:
                return ArrivalReport(False, worst, self._clock() - started,
                                     f"no measured joints for {missing}")
            worst = max(float(np.max(np.abs(
                np.asarray(measured[side], dtype=float) - want[JOINT_SLICE[side]])))
                for side in SIDES)
            if worst <= tol:
                return ArrivalReport(True, worst, self._clock() - started,
                                     "measured at the commanded posture")
            waited = self._clock() - started
            if waited >= deadline_s:
                return ArrivalReport(
                    False, worst, waited,
                    f"the worst joint is still {math.degrees(worst):.2f} deg "
                    f"from the commanded posture after {waited:.1f}s "
                    f"(tolerance {math.degrees(tol):.2f} deg)")
            self._sleep(min(self.period, max(0.0, deadline_s - waited)))

    def wait_gripper_settled(self, side: str, *, timeout_s: float = None
                             ) -> StrokeReport:
        """Poll the gripper until the stroke reaches a TERMINAL state.

        THE DAEMON'S OWN OUTCOME DECIDES, not jaw motion. ``GripperReport.kind``
        (the document's ``StrokeKind``) and ``fault_code`` say what the stroke
        did, and they are the only thing that separates "the jaws stopped on
        the object" from "the jaws stopped because the motor is disabled". This
        barrier used to accept two identical ``jaw_rad`` readings, so a faulted
        gripper — whose jaws are the stillest thing in the room — passed it as
        a completed stroke (Astra review 13; d1-2, 2026-09-22).

        In order: a fault (``HandState.fault``: a ``fault_code``, or a
        ``fault``/``overload`` outcome) is a FAILED barrier carrying the fault;
        a terminal outcome (``grasp``/``contact``/``empty``/``open``/``lost``)
        settles; ``timeout`` fails; and only an outcome that says nothing
        (``blind``, or a producer too old to publish one) falls back to jaw
        motion — two consecutive identical readings, or a reported hold.
        """
        deadline_s = (self.stroke_timeout_s if timeout_s is None
                      else float(timeout_s))
        started = self._clock()
        wire = _wire_side(side)
        previous: Optional[float] = None
        while True:
            self.renew()
            try:
                report = self.client.gripper_state(wire)
                hand = hand_state(report, commanded=self._commanded.get(side))
            except Exception as exc:  # noqa: BLE001
                return StrokeReport(False, waited_s=self._clock() - started,
                                    detail=f"the gripper cannot be read: {exc}")
            jaw = float(report.jaw_rad)
            kind = _word(report.kind) or ""
            closedness = (float("nan") if hand.closedness is None
                          else hand.closedness)
            holding = bool(hand.holding)
            waited = self._clock() - started
            if hand.fault is not None or kind in FAULT_KINDS:
                return StrokeReport(
                    False, closedness, holding, None, waited,
                    f"the stroke ended {kind or 'faulted'} "
                    f"(fault {hand.fault}) at {hand.torque_nm:.2f} Nm with the "
                    f"jaws at {jaw:.3f} rad",
                    kind=kind, fault=hand.fault or kind)
            if kind in SETTLED_KINDS:
                return StrokeReport(True, closedness, holding,
                                    stalled=hand.stalled, waited_s=waited,
                                    detail=f"the stroke ended {kind}",
                                    kind=kind)
            if kind in UNFINISHED_KINDS:
                return StrokeReport(
                    False, closedness, holding, None, waited,
                    f"the stroke ended {kind}: it ran out of time inside the "
                    f"daemon, which says nothing about where the jaws are",
                    kind=kind)
            stopped = previous is not None and abs(jaw - previous) <= 1e-6
            if holding or stopped:
                return StrokeReport(True, closedness, holding,
                                    stalled=holding or None,
                                    waited_s=waited,
                                    detail=("the producer reports a hold"
                                            if holding else
                                            "the jaws stopped moving"),
                                    kind=kind)
            previous = jaw
            if waited >= deadline_s:
                return StrokeReport(
                    False, closedness, holding, None, waited,
                    f"the stroke had not reached a terminal state after "
                    f"{waited:.1f}s (jaw {jaw:.3f} rad, still moving)",
                    kind=kind)
            self._sleep(min(self.period, max(0.0, deadline_s - waited)))

    def settle(self, timeout_s: float) -> SettleReport:
        """Poll until BOTH arms report stationary, or give up and say so.

        ``ArmState.stationary`` is the daemon's own judgement, from the same
        feedback frame it reports the velocities in. A verifier run while the
        arm is still moving measures the middle of the motion.
        """
        started = self._clock()
        worst = float("nan")
        while True:
            self.renew()
            states = [joint_state(self.client.arm_state(_wire_side(s)))
                      for s in SIDES]
            worst = max(float(np.max(np.abs(np.degrees(st.qd)))) for st in states)
            if all(st.stationary for st in states):
                return SettleReport(True, self._clock() - started, worst)
            waited = self._clock() - started
            if waited >= float(timeout_s):
                return SettleReport(
                    False, waited, worst,
                    f"still moving after {waited:.1f}s, worst joint "
                    f"{worst:.1f} deg/s")
            self._sleep(min(self.period, max(0.0, float(timeout_s) - waited)))

    # -- contact: a short trajectory, a state poll, a cancel --------------- #
    def move_until(self, path, *, side: str, criterion: ContactCriterion,
                   hz: float = None, kin=None, direction=None,
                   **_ignored) -> ContactReport:
        """Play a contact leg on the daemon, watch the torque, cancel on contact.

        POSITION MODE ONLY (Shu, 2026-09-22): nothing here sets a mode or a
        torque. The leg is uploaded as an ordinary guarded trajectory
        (``arm.arm_trajectory_start``: the daemon re-checks every sample
        against its own motion guard), the MOVING arm's generated
        ``ArmState`` is polled at this executor's rate alongside the job's
        generated ``TrajectoryStatus``, and every sample goes through the
        same :class:`~manipulation_kit.executor.ContactWatch` the streamed
        default uses. When the watch says ``confirming`` the job is cancelled
        (``arm.arm_trajectory_cancel``: "the arms hold the last accepted
        target"), which freezes the command while the rise is confirmed; a
        rise that goes away resumes the rest of the leg as a new job from the
        measured posture. Everything read comes through the generated client.

        What the document does NOT give this, and a d1-firmware issue should:
        a stop condition evaluated by the daemon's own 1 ms loop (here the
        stop latency is one HTTP poll, ~``1/hz``), the playback index or the
        setpoint in ``TrajectoryStatus`` (the frozen point is inferred from
        ``elapsed_ms``), and a tool-force estimate (``tool_force_n`` is
        therefore ``unmeasured``).
        """
        kin = contact_kin(self, kin)
        period = self.period if hz is None else 1.0 / float(hz)
        timed = [(float(t), np.asarray(q, dtype=float).reshape(7))
                 for t, q in path]
        wire = _wire_side(side)
        other = SIDES[1] if side == SIDES[0] else SIDES[0]
        self.renew()
        samples = [joint_state(self.client.arm_state(wire))
                   for _ in range(CONTACT_BASELINE_SAMPLES)]
        q_start = np.asarray(samples[0].q, dtype=float)

        def done(stopped_by: str, q_stop, *, made: bool = False,
                 watch: Optional[ContactWatch] = None, leg_t: float = 0.0,
                 elapsed: float = 0.0, detail: str = "") -> ContactReport:
            return contact_report(
                kin, side, timed, direction=direction, q_start=q_start,
                q_stop=q_stop, made=made,
                stopped_by=stopped_by,
                torque_nm=float("nan") if watch is None else watch.peak_nm,
                joint=-1 if watch is None else watch.joint, leg_t_s=leg_t,
                elapsed_s=elapsed, detail=detail)

        if criterion.tool_force_n is not None:
            return done(UNMEASURED, None, detail=(
                "the criterion asks for a TOOL FORCE and d1-firmwared "
                "publishes none; watch joint torque (tool_force_n=None)"))
        for arm in samples:
            if arm.faulted:
                return done(CONTACT_FAULT, arm.q, detail=(
                    f"the {side} arm controller reports mode {arm.mode!r} "
                    f"with error code {arm.error_code}"))
            if arm.torque_nm is None:
                return done(UNMEASURED, None, detail=(
                    f"the daemon publishes no feedback_torque for the {side} "
                    f"arm; the leg was not started"))
        watch = ContactWatch(criterion,
                             np.mean([a.torque_nm for a in samples], axis=0))
        q_other = np.degrees(joint_state(
            self.client.arm_state(_wire_side(other))).q)
        end = float(timed[-1][0])

        def upload(from_t: float, q_now) -> Any:
            """The rest of the leg, from ``from_t``, starting AT ``q_now``."""
            here = np.degrees(np.asarray(q_now, dtype=float))
            ahead = [(t - from_t, q) for t, q in timed if t > from_t + 1e-9]
            if not ahead:
                return None
            points = []
            for t, q in [(0.0, None)] + ahead:
                deg = here if q is None else np.degrees(q)
                pair = {side: deg, other: q_other}
                points.append((0.0 if q is None else INTERPOLATION_S + t,
                               pair["left"], pair["right"]))
            # checked HERE as well as in the adapter: the client is
            # replaceable (a fake, a recorder) and the check is the kit's
            check_waypoints(points)
            status = self.client.trajectory_start(
                points, holder=self.holder if self.lease is not None else None)
            job = int(status.id)
            self._jobs.append(job)
            return job

        def cancel(job) -> None:
            if job is None:
                return
            try:
                self.client.trajectory_cancel(job)
            finally:
                if job in self._jobs:
                    self._jobs.remove(job)

        started = self._clock()
        job = upload(0.0, q_start)
        job_t0 = started
        job_from = 0.0
        leg_t = 0.0
        tail = 0.0
        deadline = started + end + INTERPOLATION_S + 5.0
        try:
            while True:
                self._sleep(period)
                self.renew()
                arm = joint_state(self.client.arm_state(wire))
                now = self._clock()
                elapsed = now - started
                if job is not None:
                    status = self.client.trajectory_status(job)
                    phase = _word(status.phase) or ""
                    played = max(0.0, float(status.elapsed_ms) / 1000.0
                                 - INTERPOLATION_S)
                    leg_t = min(end, job_from + played)
                    if phase == "completed":
                        self._jobs.remove(job)
                        job, leg_t = None, end
                    elif phase in ("failed", "cancelled"):
                        self._jobs.remove(job)
                        job = None
                        if not arm.faulted:
                            return done(CONTACT_GUARD, arm.q, watch=watch,
                                        leg_t=leg_t, elapsed=elapsed, detail=(
                                            f"trajectory {status.id} {phase}: "
                                            f"{_given_text(status.message)}"))
                if arm.faulted:
                    cancel(job)
                    job = None
                    return done(CONTACT_FAULT, arm.q, watch=watch, leg_t=leg_t,
                                elapsed=elapsed, detail=(
                                    f"the {side} arm controller latched during "
                                    f"the leg: mode {arm.mode!r}, error code "
                                    f"{arm.error_code}"))
                if arm.torque_nm is None:
                    cancel(job)
                    job = None
                    return done(UNMEASURED, arm.q, watch=watch, leg_t=leg_t,
                                elapsed=elapsed,
                                detail="feedback_torque stopped being published")
                verdict = watch.sample(elapsed, arm)
                if verdict == ContactWatch.CONTACT:
                    cancel(job)
                    job = None
                    return done(CONTACT, arm.q, made=True, watch=watch,
                                leg_t=leg_t, elapsed=elapsed, detail=(
                                    f"joint {watch.joint + 1} rose "
                                    f"{watch.peak_nm:.2f} Nm over its "
                                    f"pre-motion torque (threshold "
                                    f"{criterion.joint_torque_nm:.2f} Nm)"))
                if verdict == ContactWatch.CONFIRMING:
                    # FREEZE: the daemon holds the last accepted target.
                    cancel(job)
                    job = None
                    continue
                if job is None and leg_t < end - 1e-9:
                    # A transient: resume the rest of the leg from where the
                    # arm is, as a new job (the daemon anchors on feedback).
                    job = upload(leg_t, arm.q)
                    job_from, job_t0 = leg_t, now
                    deadline = now + (end - leg_t) + INTERPOLATION_S + 5.0
                    continue
                if job is None:
                    tail += period
                    if tail >= criterion.settle_s - 1e-9:
                        return done(MAX_TRAVEL, arm.q, watch=watch, leg_t=end,
                                    elapsed=elapsed, detail=(
                                        f"travelled the whole leg and nothing "
                                        f"resisted (largest rise "
                                        f"{watch.peak_nm:.2f} Nm, threshold "
                                        f"{criterion.joint_torque_nm:.2f} Nm)"))
                elif now > deadline:
                    cancel(job)
                    job = None
                    return done(CONTACT_GUARD, arm.q, watch=watch, leg_t=leg_t,
                                elapsed=elapsed, detail=(
                                    f"the contact leg was still playing "
                                    f"{now - job_t0:.1f}s into its job; "
                                    f"cancelled"))
        except BaseException:
            cancel(job)
            raise

    def _after_contact(self, step: ContactStep, report: ContactReport,
                       index: int) -> int:
        """Relieve, hold or retract after a contact leg, as trajectory jobs.

        The same three shapes as the generic runner's
        (``executor._after_contact``): a probe is re-commanded at the posture
        it MEASURED, a press holds its frozen command (which the cancelled
        job left in place) for ``hold_s`` and then plays the leg back to its
        standoff. Returns the number of waypoints sent.
        """
        if not step.retract:
            if report.q_stop is None:
                return 0
            return self._play([JointStep(step.side, report.q_stop, index)])
        if report.made and step.hold_s > 0.0:
            self._sleep(float(step.hold_s))
        back = retract_path(step, report)
        return self._play([JointStep(step.side, q, index)
                           for _t, q in back[1:]])

    # -- the preferred path: one upload ------------------------------------ #
    def run_plan(self, plan: Plan, *, hz: float = None,
                 arrive_tol_rad: float = None,
                 arrive_timeout_s: float = None,
                 stroke_timeout_s: float = None,
                 gate: "ToolGate" = None) -> RunReport:
        """Play a pre-checked plan, trajectory-first. Used by
        :func:`manipulation_kit.executor.run` when this executor is passed.

        The BARRIERS ARE THE SAME ONES the generic runner enforces: the arm
        must be measurably at the commanded posture before a stroke, the
        stroke must reach a terminal state, and a failed settle ends the run.
        Transport ``completed`` is not any of those.

        Including the TOOL-SPACE one. A trajectory upload is still a command
        about seven angles, so a waypoint the plan marks ``arrive`` flushes
        the batch here — the arm has to be measurably ON it, at the jaw
        pocket, before the next leg is uploaded — and an uncorrectable miss
        ends the run with ``arrived_off_by`` rather than with a jaw stall two
        steps later (F17). The gate the generic runner would have used is
        passed in; with nothing passed this transport builds the same one.

        ``hz`` is the streamed transport's command rate (the trajectory upload
        is paced by the daemon), forwarded from ``run(hz=...)``; ``None``
        keeps this executor's own.

        A latched arm controller (``JointState.faulted``) stops the run with
        :data:`~manipulation_kit.executor.CONTROLLER_FAULT` — before the first
        upload, between legs, before every stroke, and in place of the
        transport error a trajectory the controller aborted ends in.
        """
        if not getattr(plan, "ok", False):
            from ...executor import REFUSED_PLAN  # noqa: PLC0415
            return RunReport(getattr(plan, "primitive", "?"),
                             getattr(plan, "side", ""), False, 0,
                             error=str(plan), stop_reason=REFUSED_PLAN)
        tol = self.arrive_tol_rad if arrive_tol_rad is None else arrive_tol_rad
        arrive_s = (self.arrive_timeout_s if arrive_timeout_s is None
                    else arrive_timeout_s)
        stroke_s = (self.stroke_timeout_s if stroke_timeout_s is None
                    else stroke_timeout_s)
        if gate is None:
            gate = ToolGate(tol_rad=tol, timeout_s=arrive_s,
                            guarded=bool(getattr(getattr(plan, "binding", None),
                                                 "guarded", True)))
        labels = arrive_labels(plan)
        self.begin_run(plan)
        if self.transport == "stream":
            # run_steps, NOT run: run() delegates to run_plan, which is this.
            from ...executor import run_steps  # noqa: PLC0415
            try:
                schedule = self.stream_schedule(plan)
            except FirmwareUnavailable as exc:
                # REFUSED BEFORE ANYTHING WAS SENT. That is the whole point:
                # a plan this transport cannot carry is not half-carried.
                return RunReport(plan.primitive, plan.side, False, 0,
                                 error=str(exc), stop_reason=TRANSPORT_ERROR)
            return run_steps(plan, self, hz=self.hz if hz is None else float(hz),
                             schedule=schedule,
                             arrive_tol_rad=tol, arrive_timeout_s=arrive_s,
                             stroke_timeout_s=stroke_s)
        sent = 0
        settle: Optional[SettleReport] = None
        arrivals: List[ArrivalReport] = []
        strokes: List[StrokeReport] = []
        contacts: List[ContactReport] = []
        batch: List[JointStep] = []
        last: Dict[str, np.ndarray] = {}

        def report(index: int, reason: str, detail: str,
                   refusal=None) -> RunReport:
            self.cancel_jobs()
            if reason != CONTROLLER_FAULT:
                # A leg the controller aborted, or a barrier it failed
                # under, is a controller fault and is reported as one.
                fault = self._fault_now()
                if fault is not None:
                    reason, detail = CONTROLLER_FAULT, fault
                    refusal = fault_refusal(plan, fault)
            return RunReport(plan.primitive, plan.side, False, sent, settle,
                             error=detail, stop_reason=reason,
                             stopped_at=index, arrivals=tuple(arrivals),
                             strokes=tuple(strokes), refusal=refusal,
                             contacts=tuple(contacts))

        try:
            fault = controller_fault(self.state())
            if fault is not None:
                # BEFORE THE FIRST BYTE. A latched arm plays nothing, and a
                # path uploaded to it is a path waiting to start the moment
                # somebody clears the error.
                return report(-1, CONTROLLER_FAULT, fault,
                              fault_refusal(plan, fault))

            def check_between(index: int):
                fault = self._fault_now()
                if fault is None:
                    return None
                return report(index, CONTROLLER_FAULT, fault,
                              fault_refusal(plan, fault))

            def gate_at(closing: JointStep, index: int):
                """Flush, then measure the TOOL at the waypoint just finished."""
                arrival, corrected = gate.check(
                    self, self._vector(last), closing.side,
                    label=labels[closing.waypoint])
                arrivals.append(arrival)
                if corrected is not None:
                    last[closing.side] = np.array(
                        corrected[JOINT_SLICE[closing.side]], dtype=float)
                if arrival.arrived:
                    return None
                refusal = barrier_refusal(plan, closing.side, arrival, gate)
                return report(index, BARRIER_FAILED, refusal.detail, refusal)

            def arrive_after(played: Sequence[JointStep], index: int, *,
                             final: bool):
                """Measure the leg just played, before anything that is
                not another joint leg. THE SAME RULE ``run_steps`` applies:
                a gated waypoint gets the tool gate; otherwise, before a
                settle and at the end of the plan, the joint-space barrier.

                Before this, the trajectory runner flushed a gated waypoint
                only when ANOTHER joint leg followed it or a stroke did, and
                ran no arrival at all before a settle or at the end: an
                Approach whose last leg ends on a settle reported
                ``completed`` with ``arrivals: []`` while its J7 sat 50 deg
                short (d1-2, 2026-09-22).
                """
                if not played or not last:
                    return None
                if played[-1].waypoint in labels:
                    return gate_at(played[-1], index)
                if not final:
                    return None
                arrival = _final_arrival(self, plan, self._vector(last),
                                         tol_rad=tol, timeout_s=arrive_s,
                                         gate=gate)
                arrivals.append(arrival)
                if arrival.arrived:
                    return None
                refusal = barrier_refusal(plan, plan.side, arrival, gate)
                return report(index, BARRIER_FAILED, arrival.detail, refusal)

            for index, step in enumerate(plan.steps):
                if isinstance(step, JointStep):
                    if (batch and step.waypoint != batch[-1].waypoint
                            and batch[-1].waypoint in labels):
                        # A GATED WAYPOINT ENDS HERE. Upload what is queued and
                        # measure before the next leg is even composed: an
                        # error carried into a descent arrives at the block.
                        closing = batch[-1]
                        sent += self._play(batch)
                        batch = []
                        stopped = check_between(index) or gate_at(closing, index)
                        if stopped is not None:
                            return stopped
                    batch.append(step)
                    last[step.side] = np.asarray(step.q, dtype=float)
                    continue
                sent += self._play(batch)
                played = batch
                batch = []
                stopped = check_between(index)
                if stopped is not None:
                    return stopped
                if isinstance(step, GripStep):
                    if last and played and played[-1].waypoint in labels:
                        # the LAST leg before a stroke is gated at the tool too
                        stopped = gate_at(played[-1], index)
                        if stopped is not None:
                            return stopped
                    elif last:
                        arrival = self.wait_arrived(self._vector(last),
                                                    tol_rad=tol,
                                                    timeout_s=arrive_s)
                        arrivals.append(arrival)
                        if not arrival.arrived:
                            return report(index, BARRIER_FAILED, arrival.detail)
                    self.set_gripper(step.side, step.closedness, grip=step.grip)
                    stroke = self.wait_gripper_settled(step.side,
                                                       timeout_s=stroke_s)
                    strokes.append(stroke)
                    if not stroke.settled:
                        refusal = stroke_refusal(plan, step.side, stroke)
                        return report(index, BARRIER_FAILED, refusal.detail,
                                      refusal)
                    refusal = hold_refusal(plan, step, stroke)
                    if refusal is not None:
                        return report(index, BARRIER_FAILED, refusal.detail,
                                      refusal)
                    sent += 1
                elif isinstance(step, SettleStep):
                    stopped = arrive_after(played, index, final=True)
                    if stopped is not None:
                        return stopped
                    settle = self.settle(step.timeout_s)
                    sent += 1
                    if not settle.settled:
                        return report(index, BARRIER_FAILED, settle.detail)
                elif isinstance(step, ContactStep):
                    stopped = arrive_after(played, index, final=False)
                    if stopped is not None:
                        return stopped
                    contact = self.move_until(
                        step.timed_path(), side=step.side,
                        criterion=step.criterion, kin=gate.kin,
                        direction=step.direction.vector())
                    contacts.append(contact)
                    if contact.stopped_by == CONTACT_FAULT:
                        fault = self._fault_now() or contact.detail
                        return report(index, CONTROLLER_FAULT, fault,
                                      fault_refusal(plan, fault))
                    if contact.stopped_by in (CONTACT_GUARD, UNMEASURED):
                        return report(index, TRANSPORT_ERROR, (
                            f"the {step.side} contact leg stopped by "
                            f"{contact.stopped_by}: {contact.detail}"))
                    sent += 1 + self._after_contact(step, contact, step.waypoint)
                    last[step.side] = np.asarray(
                        self.state().joints[step.side], dtype=float)
                else:
                    # The firmware runner used to skip an unknown step in
                    # silence while the generic one raised. Same closed set,
                    # same answer.
                    return report(index, TRANSPORT_ERROR,
                                  f"not a plan step: {step!r}")
            sent += self._play(batch)
            stopped = arrive_after(batch, len(plan.steps) - 1, final=True)
            if stopped is not None:
                return stopped
        except FirmwareUnavailable as exc:
            return report(-1, TRANSPORT_ERROR, str(exc))
        finally:
            self.end_run(plan)
        return RunReport(plan.primitive, plan.side, True, sent, settle,
                         arrivals=tuple(arrivals), strokes=tuple(strokes),
                         contacts=tuple(contacts))

    def _fault_now(self) -> Optional[str]:
        try:
            return controller_fault(self.state())
        except Exception:  # noqa: BLE001 - unreadable is not a fault; the
            return None    # transport error that follows says so

    def _vector(self, per_side: Dict[str, np.ndarray]) -> np.ndarray:
        """A 16-vector of the last commanded joints, filled from measurement.

        The arrival barrier compares BOTH arms, so the arm this plan never
        touched is compared against where it actually is.
        """
        measured = self.state().joints
        out = np.zeros(WIRE_DIM, dtype=float)
        for side in SIDES:
            q = per_side.get(side, measured.get(side))
            if q is not None:
                out[JOINT_SLICE[side]] = np.asarray(q, dtype=float)
        return out

    def _play(self, steps: Sequence[JointStep]) -> int:
        """Upload one contiguous run of joint steps as a trajectory job."""
        if not steps:
            return 0
        self.renew()
        waypoints = self._waypoints(steps)
        check_waypoints([(w["t"], w["a"], w["b"]) for w in waypoints])
        status = self.client.request("POST", "/v1/arm/trajectory/start",
                                     self._holder_body({"waypoints": waypoints}))
        job = int(status["id"])
        self._jobs.append(job)
        deadline = self._clock() + waypoints[-1]["t"] + 5.0
        try:
            while True:
                self.renew()
                status = self.client.request(
                    "GET", f"/v1/arm/trajectory/{job}/status")
                phase = str(status["phase"])
                if phase == "completed":
                    self._jobs.remove(job)
                    return len(waypoints)
                if phase in ("failed", "cancelled"):
                    self._jobs.remove(job)
                    raise FirmwareUnavailable(
                        f"trajectory {job} {phase}: {status.get('message')}")
                if self._clock() > deadline:
                    raise FirmwareUnavailable(
                        f"trajectory {job} was still running "
                        f"{waypoints[-1]['t'] + 5.0:.1f}s in; cancelled")
                self._sleep(self.period)
        except BaseException:
            # ANY way out that is not "completed" cancels the job. A polling
            # exception, a preemption, a KeyboardInterrupt: the daemon must
            # not be left playing a path nobody is watching (R6).
            self.cancel_jobs()
            raise

    def _waypoints(self, steps: Sequence[JointStep]) -> List[Dict[str, Any]]:
        """Absolute-time dual-arm waypoints, starting AT the measured pose.

        Two things happen here and both are required by the daemon. The first
        waypoint is the arms where they actually are, because a trajectory
        whose first pose is more than 3 degrees from feedback is refused. And
        every segment is stretched until no joint exceeds
        :data:`MAX_JOINT_RATE_DEG_S`, so the daemon's own 350 deg/s runtime
        slew gate has margin rather than being the thing that catches us.
        """
        measured = self.state().joints
        current = {side: np.degrees(measured[side]) for side in SIDES}
        points = [{"t": 0.0,
                   "a": [float(v) for v in current["left"]],
                   "b": [float(v) for v in current["right"]]}]
        for step in steps:
            current = dict(current)
            current[step.side] = np.degrees(np.asarray(step.q, dtype=float))
            previous = points[-1]
            span = max(max(abs(a - b) for a, b in zip(current["left"], previous["a"])),
                       max(abs(a - b) for a, b in zip(current["right"], previous["b"])))
            dt = max(self.period, span / self.max_rate)
            if previous["t"] == 0.0:
                dt = max(dt, INTERPOLATION_S)
            # Round the INTERVAL up, never the timestamp: rounding a timestamp
            # down shortens the segment and puts the commanded rate back over
            # the ceiling the interval was computed to respect.
            dt = math.ceil(dt * 1e6) / 1e6
            points.append({"t": round(previous["t"] + dt, 6),
                           "a": [float(v) for v in current["left"]],
                           "b": [float(v) for v in current["right"]]})
        return points
