"""Prove the solver is not secretly MuJoCo-shaped.

The whole reason :mod:`manipulation_kit.arms.ik` talks to a :class:`KinematicChain`
protocol rather than to a MuJoCo model is that omakase-core has no MuJoCo
dependency — it walks d1-sdk's ``pyguard``-parsed URDF with Rodrigues FK and a
geometric Jacobian. If the protocol quietly assumed MuJoCo semantics, that
consumer could not adopt the shared solver and we would keep two copies of the
part that carries the tuning and the safety behaviour.

So this module implements a chain in plain numpy — no MuJoCo, no URDF, no
d1-sdk — and shows the shared solver drives it to convergence. It is the
executable form of the claim "omakase-core can adopt this".
"""

from __future__ import annotations

import pytest

np = pytest.importorskip("numpy")
pytest.importorskip("scipy")
from scipy.spatial.transform import Rotation as R  # noqa: E402

from manipulation_kit.arms.ik import (DEFAULT_TUNING, KinematicChain,  # noqa: E402
                            clamp_joint_step, solve_ik)


class PlainNumpyChain:
    """A revolute chain with Rodrigues FK and a geometric Jacobian.

    Deliberately written the way a non-MuJoCo consumer would write it: joint
    axes and link offsets in the parent frame, accumulate transforms, then
    ``J_v = axis x (p_ee - p_joint)``, ``J_w = axis``.
    """

    def __init__(self, axes, offsets, limits):
        self._axes = [np.asarray(a, dtype=float) / np.linalg.norm(a) for a in axes]
        self._offsets = [np.asarray(o, dtype=float) for o in offsets]
        self._lo = np.asarray(limits[0], dtype=float)
        self._hi = np.asarray(limits[1], dtype=float)
        self._q = np.zeros(len(self._axes))

    @property
    def ndof(self) -> int:
        return len(self._axes)

    def joints(self):
        return self._q.copy()

    def set_joints(self, q) -> None:
        self._q = np.asarray(q, dtype=float).copy()

    def _frames(self):
        """(origin, rotation) of each joint, plus the EE, in the base frame."""
        p = np.zeros(3)
        rot = np.eye(3)
        out = []
        for axis, off, qi in zip(self._axes, self._offsets, self._q):
            p = p + rot @ off
            out.append((p.copy(), rot.copy()))
            rot = rot @ R.from_rotvec(axis * qi).as_matrix()
        return out, p, rot

    def ee_pose(self):
        _, p, rot = self._frames()
        return p, R.from_matrix(rot)

    def jacobian(self):
        frames, p_ee, _ = self._frames()
        J = np.zeros((6, self.ndof))
        for i, ((p_i, rot_i), axis) in enumerate(zip(frames, self._axes)):
            a = rot_i @ axis
            J[:3, i] = np.cross(a, p_ee - p_i)
            J[3:, i] = a
        return J

    def limits(self):
        return self._lo.copy(), self._hi.copy()


def _chain():
    # 7 revolute joints, alternating axes, 100 mm links — redundant like D1 arm
    axes = [[0, 0, 1], [0, 1, 0], [0, 0, 1], [0, 1, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0]]
    offsets = [[0, 0, 0]] + [[0.1, 0, 0]] * 6
    lim = (np.full(7, -2.6), np.full(7, 2.6))
    return PlainNumpyChain(axes, offsets, lim)


def test_chain_satisfies_the_protocol():
    assert isinstance(_chain(), KinematicChain)


def test_shared_solver_converges_on_a_non_mujoco_chain():
    """Target generated BY forward kinematics, so it is exactly reachable."""
    chain = _chain()
    q_true = np.array([0.3, -0.4, 0.5, 0.6, -0.2, 0.35, 0.1])
    chain.set_joints(q_true)
    p_t, r_t = chain.ee_pose()

    q0 = q_true + 0.15                      # seed off the solution
    chain.set_joints(q0)
    q = solve_ik(chain, p_t, r_t, q0)
    assert q is not None, "shared solver failed on a plain-numpy chain"

    chain.set_joints(q)
    p, r = chain.ee_pose()
    assert np.linalg.norm(p - p_t) < DEFAULT_TUNING.pos_tol
    assert np.linalg.norm((r_t * r.inv()).as_rotvec()) < DEFAULT_TUNING.rot_tol


def test_failed_solve_restores_the_seed():
    """A refused solve must leave the chain exactly where it was — that is what
    makes "hold the last safe pose" correct on real hardware."""
    chain = _chain()
    q0 = np.zeros(7)
    chain.set_joints(q0)
    q = solve_ik(chain, np.array([99.0, 0.0, 0.0]), R.identity(), q0)
    assert q is None
    np.testing.assert_array_equal(chain.joints(), q0)


def test_solution_is_clipped_into_limits():
    chain = _chain()
    q_true = np.array([2.4, -2.4, 2.4, 0.2, 0.0, 0.0, 0.0])
    chain.set_joints(q_true)
    p_t, r_t = chain.ee_pose()
    q = solve_ik(chain, p_t, r_t, q_true - 0.05)
    assert q is not None
    lo, hi = chain.limits()
    assert np.all(q >= lo) and np.all(q <= hi)


def test_posture_bias_pulls_toward_q_ref():
    """With a redundant chain, two solves for the SAME pose but different
    ``q_ref`` must land nearer their respective references — that is the
    null-space bias doing its job (it is what stops elbow branch flips)."""
    chain = _chain()
    q_true = np.array([0.2, -0.3, 0.4, 0.7, -0.1, 0.2, 0.0])
    chain.set_joints(q_true)
    p_t, r_t = chain.ee_pose()

    # Seed AWAY from the solution: seeded exactly on it, the solver meets
    # tolerance on the first check and returns before any iteration runs, so no
    # posture pull is ever applied and the two solves come back identical.
    q0 = q_true + 0.12
    ref_a = q_true + np.array([0.6, 0, 0, 0, 0, 0, 0])
    ref_b = q_true - np.array([0.6, 0, 0, 0, 0, 0, 0])
    qa = solve_ik(chain, p_t, r_t, q0, q_ref=ref_a)
    qb = solve_ik(chain, p_t, r_t, q0, q_ref=ref_b)
    assert qa is not None and qb is not None
    assert qa[0] > qb[0], "null-space posture pull had no effect"
    # and both still solve the task — the bias must not cost task accuracy
    for q in (qa, qb):
        chain.set_joints(q)
        p, r = chain.ee_pose()
        assert np.linalg.norm(p - p_t) < DEFAULT_TUNING.pos_tol
        assert np.linalg.norm((r_t * r.inv()).as_rotvec()) < DEFAULT_TUNING.rot_tol


def test_clamp_joint_step_scales_and_flags():
    q0 = np.zeros(4)
    q = np.array([1.0, 0.5, -0.25, 0.0])
    out, clamped = clamp_joint_step(q0, q, 0.25)
    assert clamped
    # scaled along q0 -> q, worst joint exactly at the limit
    assert np.isclose(np.max(np.abs(out - q0)), 0.25)
    np.testing.assert_allclose(out, q * 0.25)

    small = np.array([0.1, 0.0, 0.0, 0.0])
    out, clamped = clamp_joint_step(q0, small, 0.25)
    assert not clamped
    np.testing.assert_array_equal(out, small)


def test_clamp_disabled_by_non_positive_limit():
    q0 = np.zeros(3)
    q = np.array([5.0, 0.0, 0.0])
    out, clamped = clamp_joint_step(q0, q, 0.0)
    assert not clamped
    np.testing.assert_array_equal(out, q)
