"""The example is a prompt and a call; everything it must TRUST is in the wheel.

``examples/agent`` is outside the wheel (Shu, 2026-09-19) and customers read
it. Until 0.16.0 its anti-drift test asserted only that three files did not
EXIST, and it passed through every patch of 2026-09-22: eight environment
variables of operator policy, five gates, two candidate sweeps. These are the
checks that would have caught that night (design C.12), plus the example still
running end to end.
"""

from __future__ import annotations

import json
import re
from dataclasses import fields
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
AGENT = ROOT / "examples" / "agent"


# --------------------------------------------------------------------------- #
# C.12: the three checks
# --------------------------------------------------------------------------- #

def test_the_example_carries_no_policy():
    text = (AGENT / "astra_loop.py").read_text(encoding="utf-8")
    assert "os.environ" not in text
    assert "manipulation_kit.primitives.orientation" not in text, (
        "the example is doing geometry again")
    assert "from manipulation_kit.agent import" in text
    # the gates and sweeps the design deleted (D.1 rows 2, 3, 7, 9)
    for gone in ("plan_the_hand", "PLANNER_ONLY_ARGS", "_hide_planner_args",
                 "jaw_turn", "ExitStack", ".expect(", "isinstance(primitive, object)"):
        assert gone not in text, gone


@pytest.mark.xfail(strict=False,
                   reason="step 9 shrinks astra_loop.py below 200 lines")
def test_the_example_is_short():
    text = (AGENT / "astra_loop.py").read_text(encoding="utf-8")
    assert len(text.splitlines()) < 200


def test_every_operator_knob_is_a_field_of_OperatorPolicy(agent_examples):
    from manipulation_kit.agent import OperatorPolicy
    # nothing in the agent example reads the environment at all, and no
    # ASTRA_* knob survives anywhere a customer could find one
    for path in sorted(AGENT.glob("*.py")):
        assert "os.environ" not in path.read_text(encoding="utf-8"), path.name
        assert "getenv" not in path.read_text(encoding="utf-8"), path.name
    knobs = re.compile(r"ASTRA_(GRIP_CAP|APPROACH_ALLOW|VEL_RATIO|"
                       r"ARRIVE_TIMEOUT_S|SNAPSHOT_CMD|MAX_OUTPUT_TOKENS|"
                       r"REASONING|DEBUG)")
    for path in (ROOT / "examples").rglob("*"):
        if path.suffix in (".py", ".md", ".json", ".sh"):
            assert not knobs.search(path.read_text(encoding="utf-8")), path
    for path in (ROOT / "src" / "manipulation_kit" / "agent").glob("*.py"):
        assert "os.environ" not in path.read_text(encoding="utf-8"), path
    names = {f.name for f in fields(OperatorPolicy)}
    # the four robot-policy env vars of 2026-09-22, each a field now
    assert {"max_grip", "allowed_directions", "vel_ratio",
            "arrive_timeout_s"} <= names
    # ...and every field is an operator FLAG of the example
    import astra_loop
    options = {opt for action in astra_loop.build_parser()._actions
               for opt in action.option_strings}
    for name in names:
        assert OperatorPolicy.flag(name) in options, name
    assert "--policy" in options


def test_the_prompt_quotes_no_number_the_kit_owns(agent_examples):
    """Jaw millimetres, the nudge grid, the yaw clamp and the direction
    vocabulary are generated by the kit (``robot_facts``), never copied into
    the prompt where they go stale the day a hand is re-measured."""
    import astra_loop
    from manipulation_kit.agent import robot_facts
    from manipulation_kit.hands.d1.parallel_gripper.description import (
        DRIVEN_OPEN_GAP_M as JAW_OPEN_M)
    from manipulation_kit.primitives.grasp_geometry import graspable_width_m
    GRASPABLE_WIDTH_M = graspable_width_m()
    from manipulation_kit.primitives.schema import direction_doc
    from manipulation_kit.primitives.types import (NUDGE_GRID_M,
                                                   NUDGE_MAX_YAW_RAD)
    prompt = astra_loop.SYSTEM
    owned = [f"{JAW_OPEN_M * 1000:.0f}", f"{GRASPABLE_WIDTH_M * 1000:.0f}",
             f"{NUDGE_MAX_YAW_RAD * 180 / 3.141592653589793:.0f}"]
    owned += [f"{g * 1000:.0f}" for g in NUDGE_GRID_M]
    numbers = set(re.findall(r"\d+(?:\.\d+)?", prompt))
    assert not numbers & set(owned), numbers & set(owned)
    for line in direction_doc().splitlines():
        assert line.strip() not in prompt
    facts = robot_facts()
    for number in owned:
        assert number in facts, number
    for line in direction_doc().splitlines():
        assert line.strip() in facts


# --------------------------------------------------------------------------- #
# the loop, and G4
# --------------------------------------------------------------------------- #

def test_the_scripted_loop_completes_the_task_and_measures_it(agent_examples,
                                                              tmp_path):
    import astra_loop
    trace = astra_loop.loop(astra_loop.ScriptedModel(), max_turns=8,
                            trace_path=tmp_path / "trace.jsonl")
    assert trace.records
    assert trace.records[-1].goal_verdict["verdict"] == "true"
    assert trace.stop == "goal_verified"
    lines = (tmp_path / "trace.jsonl").read_text().strip().splitlines()
    assert len(lines) == len(trace.records)
    first = json.loads(lines[0])
    assert first["choice"]["name"] == "approach"
    assert first["task"] == astra_loop.DEFAULT_TASK
    assert first["observation_after"]
    # the messages are kept beside the trace, written atomically
    assert json.loads((tmp_path / "trace.messages.json").read_text())


def test_the_model_is_told_the_task_the_policy_and_the_robot(agent_examples):
    import astra_loop
    seen = {}

    class Listening(astra_loop.ScriptedModel):
        def __call__(self, messages, tools):
            seen.setdefault("first", list(messages))
            return super().__call__(messages, tools)

    astra_loop.loop(Listening(), task="put the red block in the box",
                    max_turns=1)
    text = "\n".join(str(m["content"]) for m in seen["first"])
    assert "put the red block in the box" in text
    assert "OPERATOR POLICY" in text and "ROBOT FACTS" in text


def test_a_model_that_says_done_early_does_not_end_the_run(agent_examples):
    """G4. The scripted model claims 'done' at the carry; the task verifier
    says otherwise and the loop keeps going. The trace keeps both columns."""
    import astra_loop
    trace = astra_loop.loop(astra_loop.ScriptedModel(), max_turns=8)
    claimed = [r for r in trace.records if r.claimed]
    assert claimed, "the stub no longer over-claims; the gate is untested"
    assert trace.summary()["claimed_but_unmeasured"] == 1
    assert len(trace.records) > claimed[0].iteration + 1


def test_the_loop_stops_at_max_turns_even_when_nothing_works(agent_examples):
    """The second exit. A loop with only a success exit runs all night."""
    import astra_loop

    class Stubborn:
        def __call__(self, messages, tools):
            return {"name": "grasp",
                    "arguments": {"object": "red_block", "side": "right",
                                  "direction": "down"},
                    "claimed": ""}

    trace = astra_loop.loop(Stubborn(), max_turns=3)
    assert len(trace.records) == 3
    assert trace.stop == "max_turns"
    assert all(r.verdict is None for r in trace.records)
    assert all(r.refused for r in trace.records)


def test_a_model_that_stops_still_has_the_goal_measured(agent_examples):
    import astra_loop

    class Quits:
        def __call__(self, messages, tools):
            return {"name": None, "arguments": {}, "claimed": "done"}

    trace = astra_loop.loop(Quits(), max_turns=3)
    assert trace.stop == "model_stopped"
    assert trace.records[-1].goal_verdict["verdict"] == "false"
    assert trace.summary()["claimed_but_unmeasured"] == 1


def test_two_tool_calls_in_one_turn_are_a_protocol_error(agent_examples):
    import astra_loop

    class Chatty:
        def __call__(self, messages, tools):
            return {"name": None, "arguments": {}, "call_id": "",
                    "protocol_error": "you called 2 tools", "claimed": ""}

    trace = astra_loop.loop(Chatty(), max_turns=2)
    assert len(trace.records) == 2
    assert all(r.verdict is None for r in trace.records)


def test_a_malformed_tool_call_is_answered_not_crashed_on(agent_examples):
    import astra_loop

    class Nonsense:
        def __call__(self, messages, tools):
            return {"name": "grasp", "arguments": {"nonexistent": 1},
                    "claimed": ""}

    trace = astra_loop.loop(Nonsense(), max_turns=2)
    assert len(trace.records) == 2
    assert all(r.refused for r in trace.records)


def test_the_trace_records_refusals_with_their_reasons(agent_examples):
    import astra_loop

    class AsksForTheImpossible:
        def __call__(self, messages, tools):
            return {"name": "grasp",
                    "arguments": {"object": "red_block", "side": "right",
                                  "direction": "down"},
                    "claimed": ""}

    trace = astra_loop.loop(AsksForTheImpossible(), max_turns=1)
    record = trace.records[0]
    assert record.refused and record.refused[0]["reason"]


def test_the_summary_keeps_transport_and_task_apart(agent_examples):
    import astra_loop
    trace = astra_loop.loop(astra_loop.ScriptedModel(), max_turns=8)
    summary = trace.summary()
    for key in ("transport_completed", "verdicts", "goal_verdict", "stop"):
        assert key in summary


def test_a_model_error_is_recorded_before_it_propagates(agent_examples,
                                                        tmp_path):
    """Astra review 15: failures outside ``run()`` left no record."""
    import astra_loop

    class Broken:
        def __call__(self, messages, tools):
            raise RuntimeError("the provider fell over")

    with pytest.raises(RuntimeError):
        astra_loop.loop(Broken(), max_turns=2,
                        trace_path=tmp_path / "trace.jsonl")
    record = json.loads((tmp_path / "trace.jsonl").read_text().splitlines()[-1])
    assert record["stop"] == "exception"
    assert "the provider fell over" in record["error"]


# --------------------------------------------------------------------------- #
# the menu renderer
# --------------------------------------------------------------------------- #

def test_the_jev_menu_carries_the_task_and_a_way_to_not_move(agent_examples,
                                                             d1_arm, observe):
    from menu import choice_menu
    menu = choice_menu(observe(d1_arm), d1_arm, task="put the block in the box")
    assert "put the block in the box" in menu["question"]
    assert menu["task"] == "put the block in the box"
    ids = {c["id"] for c in menu["choices"]}
    assert {"wait", "rescan", "stop"} <= ids


def test_the_menu_reports_what_the_cap_hid(agent_examples, d1_arm, observe):
    from menu import choice_menu
    menu = choice_menu(observe(d1_arm), d1_arm, task="t", cap=4)
    motions = [c for c in menu["choices"] if "index" in c]
    assert len(motions) == 4
    assert menu["hidden"]
    assert menu["offered"] == len(motions) + len(menu["hidden"])


def test_the_menu_spends_its_slots_on_task_verbs_before_corrections(
        agent_examples, d1_arm, observe):
    from menu import choice_menu
    menu = choice_menu(observe(d1_arm), d1_arm, task="t", cap=20)
    verbs = [c["verb"] for c in menu["choices"] if "verb" in c]
    assert verbs.index("grasp") < verbs.index("nudge")


def test_the_menu_interleaves_the_two_hands(agent_examples, d1_arm, observe):
    from menu import choice_menu
    menu = choice_menu(observe(d1_arm), d1_arm, task="t", cap=8)
    sides = [c["arguments"].get("side") for c in menu["choices"] if "verb" in c]
    assert "right" in sides[:8]


def test_the_jev_menu_renders_without_a_model(agent_examples, capsys):
    import jev_menu
    assert jev_menu.main([]) == 0
    printed = capsys.readouterr().out
    assert "Which single action" in printed
    assert "grasp red_block" in printed


# --------------------------------------------------------------------------- #
# the command line
# --------------------------------------------------------------------------- #

def test_the_astra_example_runs_dry(agent_examples, capsys):
    import astra_loop
    assert astra_loop.main(["--dry-run"]) == 0
    assert "CLAIMED DONE, NOT MEASURED" in capsys.readouterr().out


def test_the_tabletop_scene_runs_dry_to_a_measured_goal(agent_examples,
                                                        tmp_path, capsys):
    """The dry-run verifier of step 7, as a test: the committed scene, the
    scripted stub, the default policy (look before the stroke included)."""
    import astra_loop
    assert astra_loop.main(["--dry-run", "--executor", "kinematic",
                            "--scene", str(AGENT / "scenes" / "tabletop.json"),
                            "--object", "red_block", "--destination", "box",
                            "--trace", str(tmp_path / "t.jsonl")]) == 0
    summary = json.loads(capsys.readouterr().out.split("\n\n")[1]
                         .split("\nCLAIMED")[0])
    assert summary["stop"] == "goal_verified"
    records = [json.loads(line) for line in
               (tmp_path / "t.jsonl").read_text().splitlines()]
    assert any(r["look"] for r in records)


def test_policy_flags_reach_the_loop(agent_examples, tmp_path, capsys):
    import astra_loop
    policy = tmp_path / "policy.json"
    policy.write_text(json.dumps({"max_turns": 2}))
    assert astra_loop.main(["--dry-run", "--policy", str(policy)]) == 0
    out = capsys.readouterr().out
    assert '"turns": 2' in out and '"stop": "max_turns"' in out
    with pytest.raises(SystemExit):
        astra_loop.main(["--dry-run", "--max-grip", "crushing"])
